### ISSUE TITLE
Repeated make statement?

### ISSUE THREAD

**Issue by jackmoody11** [addisonlynch/iexfinance#140]
Is there a reason why the `make html` statement is included twice?

https://github.com/addisonlynch/iexfinance/blob/9f87066ac044de0060455bf0b282cb05217c1047/.travis.yml#L52

**Comment by addisonlynch** [comment]
Copied this config over from pandas datareader...I think we use it there because there are issues with the sphinx compiler which cause it to miss some warnings / errors on the first compilation that it should have caught. I'd like to keep this because in the ideal world the second call doesn't recompile the files which are already built anyway (no slowdown, no harm)

Good find though!
