### ISSUE TITLE
Add filter to IEX Cloud calls

### ISSUE THREAD

**Issue by someone1** [addisonlynch/iexfinance#147]
## Summary
https://iexcloud.io/docs/api/#filter-results

Let's us optimize bandwidth/weighting of each call - not to mention lowered memory footprint when processing data.

**Comment by longhao-z** [comment]
It makes a great sense to me!!!

I used get_historical_data() to download the daily close price for 500 stocks in the past year. It returned full range of info incl. open, high, low, close, volume. Since the close was what I only needed, it was a huge waste of my messages........ 

According to https://iexcloud.io/docs/api/#historical-prices, it seems be able to pull the Adjusted close via 'chartCloseOnly'.

**Comment by koljaLanger** [comment]
Maybe, I am wrong, and it does not apply in general. But I checked and at least for direct access to stock endpoints like `get_key_stats()` there is the functionality to include filters as: `get_key_stats(filter="employees,ttmDividendRate")`

**Comment by addisonlynch** [comment]
As @koljaLanger has noted, this functionality is already available via the ``filter`` keyword argument.

However, IEX does not reduce message counting for many endpoints when the filter is used (other than Key Stats with ``get_key_stats``)
